import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import test from "node:test";

import { createSetupConfig, type DetectedRepoContext } from "../src/cli/setup-config.ts";
import { writeSetupFiles } from "../src/cli/setup-files.ts";

test("writeSetupFiles creates local setup files without agent secrets", async (t) => {
  const repoRoot = await mkdtemp(path.join(os.tmpdir(), "agentrail-setup-"));
  const detectedRepo: DetectedRepoContext = {
    repoPath: repoRoot,
    remoteSlug: "oxnw/agentrail",
    defaultBranch: "main",
    gitIgnoreHasAgentrail: true,
  };

  t.after(async () => {
    await rm(repoRoot, { recursive: true, force: true });
  });

  const config = createSetupConfig({
    cwd: repoRoot,
    detectedRepo,
    interactionMode: "interactive",
    acceptedDefaults: true,
  });

  const result = await writeSetupFiles({
    repoRoot,
    config,
  });

  const configPath = path.join(repoRoot, ".agentrail", "config.json");
  const envExamplePath = path.join(repoRoot, ".agentrail", "agent.env.example");
  const envPath = path.join(repoRoot, ".agentrail", "agent.env");
  const readmePath = path.join(repoRoot, ".agentrail", "README.md");

  assert.deepEqual(
    result.writtenPaths.sort(),
    [configPath, envExamplePath, readmePath].sort(),
  );

  const configText = await readFile(configPath, "utf8");
  const configBody = JSON.parse(configText);
  const envExample = await readFile(envExamplePath, "utf8");
  const readme = await readFile(readmePath, "utf8");

  assert.equal(configBody.mode, "server");
  assert.equal(configBody.server.baseUrl, "http://127.0.0.1:3000");
  assert.doesNotMatch(configText, /apiKey|AGENTRAIL_API_KEY/);
  assert.match(envExample, /AGENTRAIL_BASE_URL=http:\/\/127\.0\.0\.1:3000/);
  assert.match(envExample, /AGENTRAIL_API_KEY=/);
  assert.match(envExample, /GITHUB_TOKEN=/);
  assert.match(envExample, /CIRCLECI_TOKEN=/);
  assert.match(envExample, /CIRCLECI_WEBHOOK_SECRET=/);
  assert.match(envExample, /init avoids capturing live secrets in terminal history/i);
  assert.equal(existsSync(envPath), false);
  assert.match(readme, /generated by `agentrail init`/i);
  assert.match(readme, /agentrail agent create/i);
  assert.match(readme, /GitHub remote slug/i);
  assert.match(readme, /`GITHUB_TOKEN`/);
  assert.match(readme, /`CIRCLECI_TOKEN`/);
  assert.match(readme, /`CIRCLECI_WEBHOOK_SECRET`/);
  assert.match(readme, /AgentRail expects `GITHUB_TOKEN`/i);
  assert.match(readme, /does not prompt for live provider tokens because init is designed to stay non-secret/i);
  assert.match(readme, /mode-0600 boundary for agent and provider credentials/i);
});
