import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import test from "node:test";

import { createSetupConfig, type DetectedRepoContext } from "../src/cli/setup-config.ts";
import { writeSetupFiles } from "../src/cli/setup-files.ts";

test("writeSetupFiles creates local setup files without agent secrets", async (t) => {
  const repoRoot = await mkdtemp(path.join(os.tmpdir(), "agentrail-setup-"));
  const homePath = await mkdtemp(path.join(os.tmpdir(), "agentrail-home-"));
  const detectedRepo: DetectedRepoContext = {
    repoPath: repoRoot,
    remoteSlug: "oxnw/agentrail",
    defaultBranch: "main",
    gitIgnoreHasAgentrail: true,
  };

  t.after(async () => {
    await rm(repoRoot, { recursive: true, force: true });
    await rm(homePath, { recursive: true, force: true });
  });

  const config = createSetupConfig({
    cwd: repoRoot,
    detectedRepo,
    interactionMode: "interactive",
    acceptedDefaults: true,
  });

  const result = await writeSetupFiles({
    homePath,
    config,
  });

  const configPath = path.join(homePath, "config.json");
  const envExamplePath = path.join(homePath, "agent.env.example");
  const serverEnvPath = path.join(homePath, "server.env");
  const envPath = path.join(homePath, "agent.env");
  const readmePath = path.join(homePath, "README.md");
  const recipePath = path.join(homePath, "agent-recipes.md");

  assert.deepEqual(
    result.writtenPaths.sort(),
    [configPath, envExamplePath, serverEnvPath, readmePath, recipePath].sort(),
  );

  const configText = await readFile(configPath, "utf8");
  const configBody = JSON.parse(configText);
  const envExample = await readFile(envExamplePath, "utf8");
  const serverEnv = await readFile(serverEnvPath, "utf8");
  const readme = await readFile(readmePath, "utf8");
  const recipe = await readFile(recipePath, "utf8");

  assert.equal(configBody.mode, "server");
  assert.equal(configBody.server.baseUrl, "http://127.0.0.1:3000");
  assert.doesNotMatch(configText, /apiKey|AGENTRAIL_API_KEY/);
  assert.match(envExample, /AGENTRAIL_BASE_URL=http:\/\/127\.0\.0\.1:3000/);
  assert.match(envExample, /AGENTRAIL_API_KEY=/);
  assert.match(envExample, /AGENTRAIL_API_KEY_ID=/);
  assert.match(envExample, new RegExp(`AGENTRAIL_AGENT_RECIPE_PATH=${escapeForRegExp(path.join(homePath, "agent-recipes.md"))}`));
  assert.doesNotMatch(envExample, /GITHUB_TOKEN=/);
  assert.doesNotMatch(envExample, /CIRCLECI_TOKEN=/);
  assert.doesNotMatch(envExample, /CIRCLECI_WEBHOOK_SECRET=/);
  assert.match(serverEnv, new RegExp(`AGENTRAIL_AGENT_AUTH_STORE_PATH=${escapeForRegExp(path.join(homePath, "stores", "agent-auth.json"))}`));
  assert.match(serverEnv, new RegExp(`AGENTRAIL_AGENT_RUNS_STORE_PATH=${escapeForRegExp(path.join(homePath, "stores", "agent-runs.json"))}`));
  assert.match(serverEnv, new RegExp(`AGENTRAIL_PROVIDER_CURSOR_STORE_PATH=${escapeForRegExp(path.join(homePath, "stores", "provider-cursors.json"))}`));
  assert.match(serverEnv, new RegExp(`AGENTRAIL_EVENT_SUBSCRIPTION_STORE_PATH=${escapeForRegExp(path.join(homePath, "stores", "event-subscriptions.json"))}`));
  assert.match(serverEnv, new RegExp(`AGENTRAIL_EVENT_DELIVERY_STORE_PATH=${escapeForRegExp(path.join(homePath, "stores", "event-deliveries.json"))}`));
  assert.doesNotMatch(serverEnv, /AGENTRAIL_PROVIDER_IDENTITY_MAPPINGS_STORE_PATH=/);
  assert.match(serverEnv, new RegExp(`AGENTRAIL_TASK_STORE_PATH=${escapeForRegExp(path.join(homePath, "stores", "tasks.json"))}`));
  assert.equal(existsSync(envPath), false);
  assert.match(readme, /generated by `agentrail init`/i);
  assert.match(readme, /agentrail agent create/i);
  assert.match(readme, /choose a runner, choose permissions, and create another local agent/i);
  assert.match(readme, /temporary local API/i);
  assert.match(readme, /already signed in to the runner you choose on this machine/i);
  assert.match(readme, /local agent profile for this machine/i);
  assert.match(readme, /server loads `~\/\.agentrail\/server\.env` automatically/i);
  assert.match(readme, /agentrail doctor/i);
  assert.match(readme, /setup is only complete when `\/tasks\/mine\?status=in_progress&limit=1` returns assigned work/i);
  assert.match(readme, /agents\/<agentId>\.env/i);
  assert.match(readme, /First connected repo/i);
  assert.match(readme, /paste the token into a hidden prompt/i);
  assert.match(readme, /provider connect github/i);
  assert.match(readme, /provider connect circleci/i);
  assert.match(readme, /provider connect linear/i);
  assert.match(readme, /linear import ENG-123/i);
  assert.match(readme, /provider list/i);
  assert.match(readme, /save them into `~\/\.agentrail\/provider\.env`/i);
  assert.doesNotMatch(readme, /Linear should send webhooks to/i);
  assert.match(readme, /Provider secrets stay out of `config\.json`/i);
  assert.match(readme, /Rules-only routing is enabled/i);
  assert.match(readme, /labels, repos, projects, and explicit rules only/i);
  assert.match(readme, /AgentRail can connect more repos later with `agentrail repo add`/i);
  assert.match(readme, /--repo "\$PWD"/);
  assert.doesNotMatch(readme, /task sources/i);
  // Core workflow instructions.
  assert.match(recipe, /Treat AgentRail as the lifecycle source of truth for every assigned task\./);
  assert.match(recipe, /Work only inside the provided git worktree for that task\./);
  const doNotEditLine = recipe.split("\n").find((line) => line.includes("Do not edit"));
  assert.ok(doNotEditLine, "Recipe should include a 'Do not edit' line");
  assert.match(doNotEditLine, /AGENTS\.md/);
  assert.match(doNotEditLine, /CLAUDE\.md/);
  assert.match(doNotEditLine, /\.agentrail\/\*/);

  // Reporting commands and handoff recovery.
  assert.match(recipe, /agentrail agent report --status progress --summary "short update"/);
  assert.match(recipe, /agentrail agent report\s+--status\s+completed\s+--summary\s+(["'])short completion summary\1\s+--handoff-file\s+(["'])\$AGENTRAIL_HANDOFF_PATH\2/);
  assert.match(recipe, /recover if the report command fails/);
  assert.match(recipe, /`target: "agentrail"`/);
  assert.match(recipe, /`target: "user"`/);

  // Safety rules.
  assert.match(recipe, /Do not expose secrets in logs, prompts, commits, or final summaries\./);
});

test("writeSetupFiles documents ai-assisted routing", async (t) => {
  const repoRoot = await mkdtemp(path.join(os.tmpdir(), "agentrail-setup-ai-"));
  const homePath = await mkdtemp(path.join(os.tmpdir(), "agentrail-home-ai-"));
  const detectedRepo: DetectedRepoContext = {
    repoPath: repoRoot,
    remoteSlug: "oxnw/agentrail",
    defaultBranch: "main",
    gitIgnoreHasAgentrail: true,
  };

  t.after(async () => {
    await rm(repoRoot, { recursive: true, force: true });
    await rm(homePath, { recursive: true, force: true });
  });

  const config = createSetupConfig({
    cwd: repoRoot,
    detectedRepo,
    interactionMode: "interactive",
    acceptedDefaults: false,
    routingMode: "ai_assist",
    routingClassifierRunner: "codex",
    routingClassifierModel: "gpt-5.4-mini",
  });

  await writeSetupFiles({ homePath, config });
  const readme = await readFile(path.join(homePath, "README.md"), "utf8");

  assert.match(readme, /use AI to route tasks to the right agents/i);
  assert.match(readme, /codex/i);
  assert.match(readme, /gpt-5\.4-mini/i);
  assert.match(readme, /Require a suitable agent/i);
  assert.match(readme, /skills or ownership areas are missing/i);
  assert.match(readme, /retries when agents are created or updated/i);
  assert.match(readme, /Local AI routing classifier timeout: 180 seconds/i);
  assert.match(readme, /up to 600 seconds/i);
});

function escapeForRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
