import { once } from "node:events";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { AgentAuthStore } from "../agent-auth-store.ts";
import { createServer } from "../app.ts";
import { AgentProfileStore } from "../agent-profile-store.ts";
import { TaskEventStore } from "../task-event-store.ts";
import { buildRuntime } from "../server-runtime.ts";
import { operatorEnvPathForHome } from "./agentrail-home.ts";
import type { SetupConfig } from "./setup-config.ts";

export interface LocalBootstrapResult {
  operatorKey: string;
  operatorKeyId: string;
  operatorEnvPath: string;
}

interface ResolvedLocalPaths {
  eventStorePath: string;
  taskStorePath: string;
  authStorePath: string;
  agentProfileStorePath: string;
  routingRuleStorePath: string;
  routingAuditStorePath: string;
}

export async function ensureLocalOperatorBootstrap({
  repoRoot,
  homePath,
  config,
}: {
  repoRoot?: string;
  homePath?: string;
  config: SetupConfig;
}): Promise<LocalBootstrapResult | null> {
  if (config.persistence.kind !== "file") {
    return null;
  }

  const resolvedHomePath = homePath ?? repoRoot;
  if (!resolvedHomePath) {
    throw new Error("ensureLocalOperatorBootstrap requires homePath.");
  }
  const operatorEnvPath = operatorEnvPathForHome(resolvedHomePath);
  const existing = await readEnvFileIfExists(operatorEnvPath);
  if (existing.AGENTRAIL_OPERATOR_KEY && existing.AGENTRAIL_OPERATOR_KEY_ID) {
    return {
      operatorKey: existing.AGENTRAIL_OPERATOR_KEY,
      operatorKeyId: existing.AGENTRAIL_OPERATOR_KEY_ID,
      operatorEnvPath,
    };
  }

  const paths = resolveLocalPaths(resolvedHomePath, config);
  const authStore = new AgentAuthStore({ storagePath: paths.authStorePath });
  const created = authStore.createKey({
    agent: {
      id: "agt_operator",
      displayName: "Local Operator",
      role: "operator",
    },
    scopes: ["auth:admin", "routing:admin", "routing:read", "tasks:read", "usage:read"],
  }, buildOperatorBootstrapIdempotencyKey(existing.AGENTRAIL_OPERATOR_KEY_ID));

  await mkdir(path.dirname(operatorEnvPath), { recursive: true });
  await writeFile(operatorEnvPath, [
    "# Generated by `agentrail init`.",
    `AGENTRAIL_BASE_URL=${config.server.baseUrl}`,
    `AGENTRAIL_OPERATOR_KEY=${created.data.apiKey}`,
    `AGENTRAIL_OPERATOR_KEY_ID=${created.data.id}`,
    "",
  ].join("\n"), { encoding: "utf8", mode: 0o600 });

  return {
    operatorKey: created.data.apiKey,
    operatorKeyId: created.data.id,
    operatorEnvPath,
  };
}

export async function hasExistingLocalAgents({
  repoRoot,
  homePath,
  config,
}: {
  repoRoot?: string;
  homePath?: string;
  config: SetupConfig;
}): Promise<boolean> {
  if (config.persistence.kind !== "file") {
    return false;
  }

  const resolvedHomePath = homePath ?? repoRoot;
  if (!resolvedHomePath) {
    throw new Error("hasExistingLocalAgents requires homePath.");
  }
  const paths = resolveLocalPaths(resolvedHomePath, config);
  const profileStore = new AgentProfileStore({ storagePath: paths.agentProfileStorePath });
  return profileStore.listProfiles().length > 0;
}

export async function withTemporaryLocalServer<T>({
  repoRoot,
  homePath,
  config,
  handler,
  validateExistingBaseUrl,
}: {
  repoRoot?: string;
  homePath?: string;
  config: SetupConfig;
  handler: (context: { baseUrl: string }) => Promise<T>;
  validateExistingBaseUrl?: (baseUrl: string) => Promise<boolean>;
}): Promise<T> {
  if (config.persistence.kind !== "file") {
    throw new Error("Temporary local server requires file persistence.");
  }

  if (await canReuseExistingServer(config.server.baseUrl, validateExistingBaseUrl)) {
    return handler({ baseUrl: config.server.baseUrl });
  }

  const resolvedHomePath = homePath ?? repoRoot;
  if (!resolvedHomePath) {
    throw new Error("withTemporaryLocalServer requires homePath.");
  }
  const paths = resolveLocalPaths(resolvedHomePath, config);
  const now = () => new Date();
  const publicBaseUrl = config.server.baseUrl;
  const eventStore = new TaskEventStore({
    now,
    storagePath: paths.eventStorePath,
  });

  const previousEnv = captureEnv([
    "AGENTRAIL_TASK_STORE_PATH",
    "AGENTRAIL_AGENT_PROFILES_STORE_PATH",
    "AGENTRAIL_ROUTING_RULES_STORE_PATH",
    "AGENTRAIL_ROUTING_AUDIT_STORE_PATH",
    "AGENTRAIL_OBSERVABILITY",
  ]);

  process.env.AGENTRAIL_TASK_STORE_PATH = paths.taskStorePath;
  process.env.AGENTRAIL_AGENT_PROFILES_STORE_PATH = paths.agentProfileStorePath;
  process.env.AGENTRAIL_ROUTING_RULES_STORE_PATH = paths.routingRuleStorePath;
  process.env.AGENTRAIL_ROUTING_AUDIT_STORE_PATH = paths.routingAuditStorePath;
  process.env.AGENTRAIL_OBSERVABILITY = "false";

  try {
    const runtime = buildRuntime({
      githubToken: process.env.GITHUB_TOKEN || null,
      circleciToken: process.env.CIRCLECI_TOKEN || null,
      now,
      eventStore,
      publicBaseUrl,
    });
    const authStore = new AgentAuthStore({ now, storagePath: paths.authStorePath });
    const server = createServer({
      store: eventStore,
      taskLifecycleStore: runtime.taskLifecycleStore,
      ciStatusAdapter: runtime.ciStatusAdapter,
      reviewFeedbackAdapter: runtime.reviewFeedbackAdapter,
      rollbackAdapter: runtime.rollbackAdapter,
      intakeAdapter: runtime.intakeAdapter,
      routingControlPlane: runtime.routingControlPlane,
      authStore,
      now,
      publicBaseUrl,
      fallbackMode: false,
    });
    try {
      const listenResult = await listen(
        server,
        0,
        config.server.host,
        config.server.baseUrl,
        validateExistingBaseUrl,
      );
      if (listenResult.mode === "reuse_existing") {
        await closeServer(server);
        return await handler({ baseUrl: config.server.baseUrl });
      }

      const address = server.address();
      if (!address || typeof address === "string") {
        throw new Error("Temporary local server did not expose a TCP address.");
      }

      const baseUrl = `http://${address.address}:${address.port}`;
      return await handler({ baseUrl });
    } finally {
      await closeServer(server);
    }
  } finally {
    restoreEnv(previousEnv);
  }
}

function resolveLocalPaths(homePath: string, config: SetupConfig): ResolvedLocalPaths {
  if (config.persistence.kind !== "file") {
    throw new Error("Local file paths require file persistence.");
  }

  return {
    eventStorePath: path.resolve(homePath, config.persistence.eventStorePath),
    taskStorePath: path.resolve(homePath, config.persistence.taskStorePath),
    authStorePath: path.resolve(homePath, config.persistence.authStorePath),
    agentProfileStorePath: path.resolve(homePath, config.persistence.agentProfileStorePath),
    routingRuleStorePath: path.resolve(homePath, config.persistence.routingRuleStorePath),
    routingAuditStorePath: path.resolve(homePath, config.persistence.routingAuditStorePath),
  };
}

function buildOperatorBootstrapIdempotencyKey(existingKeyId: string | undefined): string {
  return existingKeyId
    ? `local-operator-bootstrap-${existingKeyId}`
    : "local-operator-bootstrap-v1";
}

async function readEnvFileIfExists(filePath: string): Promise<Record<string, string>> {
  try {
    return parseEnvFile(await readFile(filePath, "utf8"));
  } catch {
    return {};
  }
}

function parseEnvFile(content: string): Record<string, string> {
  const parsed: Record<string, string> = {};
  for (const rawLine of content.split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separatorIndex = line.indexOf("=");
    if (separatorIndex === -1) continue;
    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    if (!key) continue;
    parsed[key] = value.replace(/^"(.*)"$/u, "$1").replace(/^'(.*)'$/u, "$1");
  }
  return parsed;
}

function captureEnv(keys: string[]): Record<string, string | undefined> {
  return Object.fromEntries(keys.map((key) => [key, process.env[key]]));
}

function restoreEnv(values: Record<string, string | undefined>) {
  for (const [key, value] of Object.entries(values)) {
    if (value === undefined) {
      delete process.env[key];
      continue;
    }
    process.env[key] = value;
  }
}

async function listen(
  server: ReturnType<typeof createServer>,
  port: number,
  host: string,
  baseUrl: string,
  validateExistingBaseUrl?: (baseUrl: string) => Promise<boolean>,
): Promise<{ mode: "started_temp" | "reuse_existing" }> {
  return await new Promise<{ mode: "started_temp" | "reuse_existing" }>((resolve, reject) => {
    const attach = (requestedPort: number) => {
      const onError = async (error: NodeJS.ErrnoException) => {
        server.off("listening", onListening);
        if (error.code === "EADDRINUSE" && requestedPort !== 0) {
          if (await canReuseExistingServer(baseUrl, validateExistingBaseUrl)) {
            resolve({ mode: "reuse_existing" });
            return;
          }
          attach(0);
          return;
        }
        reject(error);
      };
      const onListening = () => {
        server.off("error", onError);
        resolve({ mode: "started_temp" });
      };

      server.once("error", onError);
      server.once("listening", onListening);
      server.listen(requestedPort, host);
    };
    attach(port);
  });
}

function closeServer(server: ReturnType<typeof createServer>): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      server.close((error) => {
        const serverError = error as NodeJS.ErrnoException | undefined;
        if (serverError && serverError.code !== "ERR_SERVER_NOT_RUNNING") {
          reject(serverError);
          return;
        }
        resolve();
      });
    } catch (error) {
      if (
        typeof error === "object"
        && error !== null
        && "code" in error
        && error.code === "ERR_SERVER_NOT_RUNNING"
      ) {
        resolve();
        return;
      }
      reject(error);
    }
  });
}

async function isHealthyServer(baseUrl: string): Promise<boolean> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 3_000);
  try {
    const response = await fetch(new URL("health", `${baseUrl.replace(/\/+$/, "")}/`), {
      signal: controller.signal,
    });
    if (!response.ok) {
      return false;
    }
    const json = await response.json().catch(() => null);
    return json?.status === "ok";
  } catch {
    return false;
  } finally {
    clearTimeout(timeoutId);
  }
}

async function canReuseExistingServer(
  baseUrl: string,
  validateExistingBaseUrl?: (baseUrl: string) => Promise<boolean>,
): Promise<boolean> {
  if (!await isHealthyServer(baseUrl)) {
    return false;
  }
  if (!validateExistingBaseUrl) {
    return true;
  }
  try {
    return await validateExistingBaseUrl(baseUrl);
  } catch {
    return false;
  }
}
