import path from "node:path";
import { mkdir, rm, writeFile } from "node:fs/promises";

import type { SetupConfig } from "./setup-config.ts";
import { agentEnvExamplePathForHome, configPathForHome, currentAgentEnvPathForHome, recipePathForHome, serverEnvPathForHome } from "./agentrail-home.ts";

export interface WriteSetupFilesOptions {
  homePath?: string;
  repoRoot?: string;
  config: SetupConfig;
}

export interface WriteSetupFilesResult {
  writtenPaths: string[];
}

export async function writeSetupFiles({
  homePath,
  repoRoot,
  config,
}: WriteSetupFilesOptions): Promise<WriteSetupFilesResult> {
  const resolvedHomePath = homePath ?? repoRoot;
  if (!resolvedHomePath) {
    throw new Error("writeSetupFiles requires homePath or repoRoot.");
  }
  const configPath = configPathForHome(resolvedHomePath);
  const envExamplePath = agentEnvExamplePathForHome(resolvedHomePath);
  const serverEnvPath = serverEnvPathForHome(resolvedHomePath);
  const readmePath = path.join(resolvedHomePath, "README.md");
  const recipePath = recipePathForHome(resolvedHomePath);
  const writtenPaths = [configPath, envExamplePath, serverEnvPath, readmePath, recipePath];

  await mkdir(resolvedHomePath, { recursive: true });
  if (config.exports.markdown.enabled) {
    await mkdir(path.join(resolvedHomePath, config.exports.markdown.path), { recursive: true });
  }
  if (config.persistence.kind === "file") {
    await mkdir(path.join(resolvedHomePath, "stores"), { recursive: true });
    // Older local installs may still have this removed store on disk; drop it whenever
    // setup rewrites the home so the generated state matches the current model.
    await rm(path.join(resolvedHomePath, "stores", "provider-identity-mappings.json"), { force: true });
  }
  await mkdir(path.join(resolvedHomePath, "agents"), { recursive: true });

  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
  await writeFile(envExamplePath, renderAgentEnvExample(config, resolvedHomePath), "utf8");
  await writeFile(serverEnvPath, renderServerEnv(config, resolvedHomePath), { encoding: "utf8", mode: 0o600 });
  await writeFile(readmePath, renderSetupReadme(config), "utf8");
  await writeFile(recipePath, renderDefaultRecipe(), "utf8");

  return { writtenPaths };
}

function renderServerEnv(config: SetupConfig, homePath: string): string {
  const lines = [
    "# Generated by `agentrail init`.",
    `AGENTRAIL_HOST=${config.server.host}`,
    `AGENTRAIL_PORT=${config.server.port}`,
    `AGENTRAIL_PUBLIC_BASE_URL=${config.server.baseUrl}`,
  ];

  if (config.persistence.kind === "file") {
    lines.push(
      `AGENTRAIL_EVENT_STORE_PATH=${path.resolve(homePath, config.persistence.eventStorePath)}`,
      `AGENTRAIL_TASK_STORE_PATH=${path.resolve(homePath, config.persistence.taskStorePath)}`,
      `AGENTRAIL_AGENT_AUTH_STORE_PATH=${path.resolve(homePath, config.persistence.authStorePath)}`,
      `AGENTRAIL_AGENT_RUNS_STORE_PATH=${path.resolve(homePath, config.persistence.agentRunStorePath)}`,
      `AGENTRAIL_PROVIDER_CURSOR_STORE_PATH=${path.resolve(homePath, config.persistence.providerCursorStorePath)}`,
      `AGENTRAIL_EVENT_SUBSCRIPTION_STORE_PATH=${path.resolve(homePath, config.persistence.eventSubscriptionStorePath)}`,
      `AGENTRAIL_EVENT_DELIVERY_STORE_PATH=${path.resolve(homePath, config.persistence.eventDeliveryStorePath)}`,
      `AGENTRAIL_AGENT_PROFILES_STORE_PATH=${path.resolve(homePath, config.persistence.agentProfileStorePath)}`,
      `AGENTRAIL_ROUTING_RULES_STORE_PATH=${path.resolve(homePath, config.persistence.routingRuleStorePath)}`,
      `AGENTRAIL_ROUTING_AUDIT_STORE_PATH=${path.resolve(homePath, config.persistence.routingAuditStorePath)}`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

function renderAgentEnvExample(config: SetupConfig, homePath: string): string {
  return [
    "# Generated by `agentrail init`.",
    "# `agentrail agent create` writes `~/.agentrail/agents/<agentId>.env` later with mode 0600.",
    "# It may also refresh `~/.agentrail/agent.env` as the default local alias for the current agent.",
    "# Provider credentials stay blank here because init avoids capturing live secrets in terminal history.",
    `AGENTRAIL_BASE_URL=${config.server.baseUrl}`,
    "AGENTRAIL_API_KEY=",
    "AGENTRAIL_API_KEY_ID=",
    "AGENTRAIL_AGENT_ID=",
    "AGENTRAIL_AGENT_RUNNER=",
    "# Comma-separated GitHub repo slugs. `agentrail init` uses your first connected repo as the first entry.",
    `AGENTRAIL_REPO_ALLOWLIST=${config.repos.map((repo) => repo.slug).join(",")}`,
    `AGENTRAIL_AGENT_RECIPE_PATH=${recipePathForHome(homePath)}`,
    "",
  ].join("\n");
}

function renderSetupReadme(config: SetupConfig): string {
  const primaryRepo = config.repos[0];
  return [
    "# AgentRail Local Home",
    "",
    "This directory was generated by `agentrail init`.",
    "",
    "## Files",
    "",
    "- `config.json`: non-secret orchestrator setup state for local/self-hosted runs.",
    "- `server.env`: local server/runtime env defaults written by setup.",
    "- `agent.env.example`: placeholder environment file until `agentrail agent create` writes `agents/<agentId>.env`.",
    "- `agents/`: generated per-agent env files.",
    "- `agent.env`: current-agent alias used by commands like `agentrail doctor`.",
    "- `agent-recipes.md`: default instructions file for new agents.",
    "- `README.md`: setup notes and next commands.",
    "",
    "## Connected repos",
    "",
    `- First connected repo: \`${primaryRepo?.path ?? ""}\`.`,
    `- GitHub repo: \`${primaryRepo?.slug ?? ""}\` (${toGitHubUrl(primaryRepo?.slug ?? "")}).`,
    "- AgentRail can connect more repos later with `agentrail repo add`.",
    "",
    "## GitHub, CircleCI, and Linear",
    "",
    "- Interactive `agentrail init` can optionally connect GitHub immediately by asking you to paste the token into a hidden prompt.",
    "- Use `agentrail provider connect github` to connect GitHub and choose polling or webhook delivery.",
    "- Use `agentrail provider connect circleci` to connect CircleCI, choose polling or webhook delivery, and paste the full CircleCI project slug for each connected repo.",
    "  AgentRail verifies project access, creates `.circleci/config.yml` for straightforward Node repos when missing, configures an API-trigger fallback when CircleCI exposes a pipeline definition, and reports exact external blockers when setup cannot be fixed locally.",
    "- Use `agentrail provider connect linear` to connect Linear and choose polling or webhook delivery.",
    "- Use `agentrail linear import ENG-123` to import a Linear issue locally.",
    "- Use `agentrail provider list` to review which providers are configured locally.",
    "- Interactive provider commands ask you to paste secrets into hidden prompts, then save them into `~/.agentrail/provider.env` for local use.",
    "- Non-interactive provider commands can still read credentials from env vars for automation or CI.",
    `- Webhook delivery is only available when AgentRail is reachable on a public HTTPS base URL such as \`https://your-domain.com\` (local URL \`${config.server.baseUrl}\` will not work for webhooks).`,
    "",
    "## Routing",
    "",
    config.routing.mode === "ai_assist"
      ? `- AgentRail will use AI to route tasks to the right agents with ${config.routing.classifier.runner}${config.routing.classifier.model ? ` (${config.routing.classifier.model})` : ""}.`
      : "- Rules-only routing is enabled. AgentRail will use labels, repos, projects, and explicit rules only.",
    config.routing.mode === "ai_assist"
      ? describeAiRoutingFallback(config.routing.classifier.fallbackBehavior)
      : "- If no rule matches, AgentRail leaves the task for operator review.",
    config.routing.mode === "ai_assist"
      ? `- Local AI routing classifier timeout: ${Math.round(config.routing.classifier.timeoutMs / 1000)} seconds by default. Slow local runners can raise \`routing.classifier.timeoutMs\` up to 600 seconds in \`config.json\`.`
      : "",
    "",
    "## Local agent access",
    "",
    `- Local agents use the \`${config.runnerPolicy.preset.replace(/_/gu, "-")}\` runner policy by default.`,
    "- AgentRail strips broad provider credentials from managed child runners and keeps pull request creation, shipping, and rollback inside AgentRail unless you change the policy.",
    "- `agentrail doctor` reports whether the selected local runner can enforce this policy.",
    "",
    "## Next Steps",
    "",
    "1. Run `agentrail agent create` to choose a runner, choose permissions, and create another local agent.",
    "   If the local API is not already running, AgentRail starts a temporary local API to create the agent and then shuts it down.",
    "   AgentRail writes the runner connection file for you and can remember this as the local agent profile for this machine.",
    "   Make sure you are already signed in to the runner you choose on this machine.",
    "2. Start the local API with `agentrail server start`; it processes provider polling/webhooks and keeps configured local agents awake.",
    "   The server loads `~/.agentrail/server.env` automatically.",
    "3. Run `agentrail doctor`; setup is only complete when `/tasks/mine?status=in_progress&limit=1` returns assigned work for that agent.",
    "   Use `agentrail agent run --once --env-file ~/.agentrail/agents/<agentId>.env` only for manual debugging.",
    "4. Optionally connect GitHub immediately from the init follow-up prompt, or use `agentrail provider connect github`, `agentrail provider connect circleci`, or `agentrail provider connect linear` later.",
    "5. After connecting Linear, import issues with `agentrail linear import ENG-123`.",
    "6. Provider secrets stay out of `config.json` and are written only to `~/.agentrail/provider.env`.",
    `7. For automation or CI, you can still reproduce this setup non-interactively with: \`${renderPortableInitCommand(config)}\`.`,
    "",
  ].join("\n");
}

function renderDefaultRecipe(): string {
  return [
    "# AgentRail Agent Instructions",
    "",
    "This file is passed to local runners created by AgentRail.",
    "Treat AgentRail as the lifecycle source of truth for every assigned task.",
    "",
    "## Required Flow",
    "",
    "1. Read the assigned task from the AgentRail-provided run prompt before editing anything.",
    "2. Work only inside the provided git worktree for that task.",
    "3. Do not hand-roll AgentRail API calls, push branches, create pull requests, ship, or roll back directly; use `agentrail agent report` for status updates.",
    "4. Report meaningful progress with `agentrail agent report --status progress --summary \"short update\"`.",
    "5. If blocked, report the blocker with `agentrail agent report --status blocked --summary \"what user action is needed\" --reason \"short reason\" --action-required \"what the user must do\" --resume-instructions \"how to continue after the user acts\"`.",
    "6. For any blocker, also write a `target: \"user\"` handoff file at `$AGENTRAIL_HANDOFF_PATH` so AgentRail can recover if the report command fails.",
    "7. Run the smallest relevant validation before reporting completion.",
    "8. Commit locally when the task requires a code change.",
    "9. Write the structured handoff JSON file at `$AGENTRAIL_HANDOFF_PATH` before exiting. AgentRail provides this environment variable at runtime; users do not set it manually.",
    "10. Report completion with `agentrail agent report --status completed --summary \"short completion summary\" --handoff-file \"$AGENTRAIL_HANDOFF_PATH\"`.",
    "11. Use `target: \"agentrail\"` when AgentRail should publish and continue the lifecycle.",
    "12. Use `target: \"user\"` when missing credentials, provider failures, sandbox restrictions, tooling, or validation failures require user intervention.",
    "",
    "## Handoff Contract",
    "",
    "- AgentRail owns publishing, pull request creation, CI reads, review reads, shipping, and rollback.",
    "- For `target: \"agentrail\"`, write JSON with `version`, `target`, `summary`, `commitSha`, and optional `checks`, `artifacts`, and `pullRequest`.",
    "- For `target: \"user\"`, write JSON with `version`, `target`, `summary`, `reason`, `actionRequired`, and `resumeInstructions`.",
    "- Do not edit `AGENTS.md`, `CLAUDE.md`, `.agentrail/*`, or other instruction files unless the task explicitly asks for that change.",
    "- Do not expose secrets in logs, prompts, commits, or final summaries.",
    "",
  ].join("\n");
}

function toGitHubUrl(slug: string): string {
  return slug ? `https://github.com/${slug}` : "";
}

function renderPortableInitCommand(config: SetupConfig): string {
  const parts = [
    "agentrail init",
    `--mode ${config.mode}`,
    `--base-url ${config.server.baseUrl}`,
    `--port ${config.server.port}`,
    `--persistence ${config.persistence.kind}`,
    '--repo "$PWD"',
    `--repo-allowlist ${config.repos.map((repo) => repo.slug).join(",")}`,
    `--default-branch ${config.repos[0]?.defaultBranch ?? "main"}`,
  ];

  if (config.providers.github.mode !== "real") {
    parts.push(`--provider-mode ${config.providers.github.mode}`);
  }

  if (config.exports.markdown.enabled) {
    parts.push("--markdown-export");
  }
  if (config.runnerPolicy.preset !== "strict") {
    parts.push(`--runner-policy ${config.runnerPolicy.preset.replace(/_/gu, "-")}`);
  }
  if (config.routing.mode === "ai_assist") {
    parts.push("--routing-mode ai-assist");
    parts.push(`--routing-classifier-runner ${config.routing.classifier.runner}`);
    if (config.routing.classifier.model) {
      parts.push(`--routing-classifier-model ${config.routing.classifier.model}`);
    }
    parts.push(`--routing-confidence-threshold ${config.routing.classifier.confidenceThreshold}`);
    parts.push(`--routing-no-suitable-agent ${config.routing.classifier.fallbackBehavior.replace(/_/gu, "-")}`);
  }

  return parts.join(" ");
}

function describeAiRoutingFallback(fallbackBehavior: string): string {
  if (fallbackBehavior === "assign_closest_match") {
    return "- Assign the closest match: If AI routing cannot find a suitable agent, AgentRail assigns the best available agent and records a best-effort explanation.";
  }
  return "- Require a suitable agent: If AI routing cannot find a suitable agent, AgentRail leaves the task unassigned, explains what agent skills or ownership areas are missing, and retries when agents are created or updated.";
}
