import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";

import { buildInitCommand, type SetupConfig } from "./setup-config.ts";

export interface WriteSetupFilesOptions {
  repoRoot: string;
  config: SetupConfig;
}

export interface WriteSetupFilesResult {
  writtenPaths: string[];
}

export async function writeSetupFiles({
  repoRoot,
  config,
}: WriteSetupFilesOptions): Promise<WriteSetupFilesResult> {
  const agentrailDir = path.join(repoRoot, ".agentrail");
  const configPath = path.join(agentrailDir, "config.json");
  const envExamplePath = path.join(agentrailDir, "agent.env.example");
  const readmePath = path.join(agentrailDir, "README.md");
  const writtenPaths = [configPath, envExamplePath, readmePath];

  await mkdir(agentrailDir, { recursive: true });
  if (config.exports.markdown.enabled) {
    await mkdir(path.join(repoRoot, config.exports.markdown.path), { recursive: true });
  }

  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
  await writeFile(envExamplePath, renderAgentEnvExample(config), "utf8");
  await writeFile(readmePath, renderSetupReadme(config), "utf8");

  return { writtenPaths };
}

function renderAgentEnvExample(config: SetupConfig): string {
  const recipePath = path.join(config.targetRepo.path, "docs", "agent-recipes.md");

  return [
    "# Generated by `agentrail init`.",
    "# `agentrail agent create` writes `.agentrail/agent.env` later with mode 0600.",
    "# Provider credentials stay blank here because init avoids capturing live secrets in terminal history or repo-scoped setup files.",
    `AGENTRAIL_BASE_URL=${config.server.baseUrl}`,
    "AGENTRAIL_API_KEY=",
    "AGENTRAIL_AGENT_ID=",
    "AGENTRAIL_AGENT_RUNNER=",
    "# Comma-separated GitHub repo slugs. `agentrail init` seeds the detected remote as the first entry.",
    `AGENTRAIL_REPO_ALLOWLIST=${config.targetRepo.allowlist.join(",")}`,
    `AGENTRAIL_AGENT_RECIPE_PATH=${recipePath}`,
    `${config.providers.github.tokenEnv}=`,
    `${config.providers.circleci.tokenEnv}=`,
    `${config.providers.circleci.webhookSecretEnv}=`,
    "",
  ].join("\n");
}

function renderSetupReadme(config: SetupConfig): string {
  return [
    "# AgentRail Local Setup",
    "",
    "This directory was generated by `agentrail init`.",
    "",
    "## Files",
    "",
    "- `config.json`: non-secret setup state for local/self-hosted runs.",
    "- `agent.env.example`: placeholder environment file until `agentrail agent create` writes `.agentrail/agent.env`.",
    "- `README.md`: setup notes and next commands.",
    "",
    "## GitHub and CircleCI",
    "",
    `- Target GitHub checkout: \`${config.targetRepo.path}\`. AgentRail works against this local checkout when it prepares task, review, and CI operations.`,
    `- GitHub remote slug: \`${config.targetRepo.allowlist[0]}\`. AgentRail stores this in \`AGENTRAIL_REPO_ALLOWLIST\` as the first allowed repository entry.`,
    "- AgentRail expects `GITHUB_TOKEN` for GitHub submit/review/CI adapters and `CIRCLECI_TOKEN` plus `CIRCLECI_WEBHOOK_SECRET` for CircleCI status polling and webhook verification.",
    `- CircleCI should send webhooks to \`${config.server.baseUrl}/providers/circleci/webhooks\` after the server is running.`,
    "",
    "## Next Steps",
    "",
    "1. Start the local API with `npm start` after you have configured the required environment variables and task sources.",
    "2. Fill `.agentrail/agent.env` from the example after you mint the agent key and choose the final `AGENTRAIL_AGENT_ID`; future `agentrail agent create/connect` work will automate this step.",
    "3. Export an operator/setup key as `AGENTRAIL_SETUP_API_KEY` and run `agentrail doctor`; setup is only complete when `/tasks/mine?status=in_progress&limit=1` returns assigned work for that agent.",
    "4. If you are enabling live providers, copy the `GITHUB_TOKEN`, `CIRCLECI_TOKEN`, and `CIRCLECI_WEBHOOK_SECRET` placeholders into `.agentrail/agent.env` after registration.",
    "5. `agentrail init` does not prompt for live provider tokens because init is designed to stay non-secret and safe to rerun; `.agentrail/agent.env` is the later mode-0600 boundary for agent and provider credentials.",
    `6. For automation or CI, you can still reproduce this setup non-interactively with: \`${buildInitCommand(config)}\`.`,
    "",
  ].join("\n");
}
