import path from "node:path";
import { mkdir, rm, writeFile } from "node:fs/promises";

import type { SetupConfig } from "./setup-config.ts";
import { agentEnvExamplePathForHome, configPathForHome, currentAgentEnvPathForHome, recipePathForHome, serverEnvPathForHome } from "./agentrail-home.ts";

export interface WriteSetupFilesOptions {
  homePath?: string;
  repoRoot?: string;
  config: SetupConfig;
}

export interface WriteSetupFilesResult {
  writtenPaths: string[];
}

export async function writeSetupFiles({
  homePath,
  repoRoot,
  config,
}: WriteSetupFilesOptions): Promise<WriteSetupFilesResult> {
  const resolvedHomePath = homePath ?? repoRoot;
  if (!resolvedHomePath) {
    throw new Error("writeSetupFiles requires homePath or repoRoot.");
  }
  const configPath = configPathForHome(resolvedHomePath);
  const envExamplePath = agentEnvExamplePathForHome(resolvedHomePath);
  const serverEnvPath = serverEnvPathForHome(resolvedHomePath);
  const readmePath = path.join(resolvedHomePath, "README.md");
  const recipePath = recipePathForHome(resolvedHomePath);
  const writtenPaths = [configPath, envExamplePath, serverEnvPath, readmePath, recipePath];

  await mkdir(resolvedHomePath, { recursive: true });
  if (config.exports.markdown.enabled) {
    await mkdir(path.join(resolvedHomePath, config.exports.markdown.path), { recursive: true });
  }
  if (config.persistence.kind === "file") {
    await mkdir(path.join(resolvedHomePath, "stores"), { recursive: true });
    // Older local installs may still have this removed store on disk; drop it whenever
    // setup rewrites the home so the generated state matches the current model.
    await rm(path.join(resolvedHomePath, "stores", "provider-identity-mappings.json"), { force: true });
  }
  await mkdir(path.join(resolvedHomePath, "agents"), { recursive: true });

  await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
  await writeFile(envExamplePath, renderAgentEnvExample(config, resolvedHomePath), "utf8");
  await writeFile(serverEnvPath, renderServerEnv(config, resolvedHomePath), { encoding: "utf8", mode: 0o600 });
  await writeFile(readmePath, renderSetupReadme(config), "utf8");
  await writeFile(recipePath, renderDefaultRecipe(), "utf8");

  return { writtenPaths };
}

function renderServerEnv(config: SetupConfig, homePath: string): string {
  const lines = [
    "# Generated by `agentrail init`.",
    `AGENTRAIL_HOST=${config.server.host}`,
    `AGENTRAIL_PORT=${config.server.port}`,
    `AGENTRAIL_PUBLIC_BASE_URL=${config.server.baseUrl}`,
  ];

  if (config.persistence.kind === "file") {
    lines.push(
      `AGENTRAIL_EVENT_STORE_PATH=${path.resolve(homePath, config.persistence.eventStorePath)}`,
      `AGENTRAIL_TASK_STORE_PATH=${path.resolve(homePath, config.persistence.taskStorePath)}`,
      `AGENTRAIL_AGENT_AUTH_STORE_PATH=${path.resolve(homePath, config.persistence.authStorePath)}`,
      `AGENTRAIL_AGENT_PROFILES_STORE_PATH=${path.resolve(homePath, config.persistence.agentProfileStorePath)}`,
      `AGENTRAIL_ROUTING_RULES_STORE_PATH=${path.resolve(homePath, config.persistence.routingRuleStorePath)}`,
      `AGENTRAIL_ROUTING_AUDIT_STORE_PATH=${path.resolve(homePath, config.persistence.routingAuditStorePath)}`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

function renderAgentEnvExample(config: SetupConfig, homePath: string): string {
  return [
    "# Generated by `agentrail init`.",
    "# `agentrail agent create` writes `~/.agentrail/agents/<agentId>.env` later with mode 0600.",
    "# It may also refresh `~/.agentrail/agent.env` as the default local alias for the current agent.",
    "# Provider credentials stay blank here because init avoids capturing live secrets in terminal history.",
    `AGENTRAIL_BASE_URL=${config.server.baseUrl}`,
    "AGENTRAIL_API_KEY=",
    "AGENTRAIL_API_KEY_ID=",
    "AGENTRAIL_AGENT_ID=",
    "AGENTRAIL_AGENT_RUNNER=",
    "# Comma-separated GitHub repo slugs. `agentrail init` uses your first connected repo as the first entry.",
    `AGENTRAIL_REPO_ALLOWLIST=${config.repos.map((repo) => repo.slug).join(",")}`,
    `AGENTRAIL_AGENT_RECIPE_PATH=${recipePathForHome(homePath)}`,
    "",
  ].join("\n");
}

function renderSetupReadme(config: SetupConfig): string {
  const primaryRepo = config.repos[0];
  return [
    "# AgentRail Local Home",
    "",
    "This directory was generated by `agentrail init`.",
    "",
    "## Files",
    "",
    "- `config.json`: non-secret orchestrator setup state for local/self-hosted runs.",
    "- `server.env`: local server/runtime env defaults written by setup.",
    "- `agent.env.example`: placeholder environment file until `agentrail agent create` writes `agents/<agentId>.env`.",
    "- `agents/`: generated per-agent env files.",
    "- `agent.env`: current-agent alias used by commands like `agentrail doctor`.",
    "- `agent-recipes.md`: default instructions file for new agents.",
    "- `README.md`: setup notes and next commands.",
    "",
    "## Connected repos",
    "",
    `- First connected repo: \`${primaryRepo?.path ?? ""}\`.`,
    `- GitHub repo: \`${primaryRepo?.slug ?? ""}\` (${toGitHubUrl(primaryRepo?.slug ?? "")}).`,
    "- AgentRail can connect more repos later with `agentrail repo add`.",
    "",
    "## GitHub and CircleCI",
    "",
    "- Interactive `agentrail init` can optionally connect GitHub immediately with a masked token prompt.",
    "- Use `./agentrail provider connect github` to connect GitHub.",
    "- Use `./agentrail provider connect circleci` to connect CircleCI.",
    "- Use `./agentrail provider list` to review which providers are configured locally.",
    `- CircleCI should send webhooks to \`${config.server.baseUrl}/providers/circleci/webhooks\` after the server is running.`,
    "- Interactive provider commands prompt for secrets without echoing them, then save them into `~/.agentrail/provider.env` for local use.",
    "- Non-interactive provider commands can still read credentials from env vars for automation or CI.",
    "",
    "## Next Steps",
    "",
    "1. Start the local API with `./agentrail server start`; the server will load `~/.agentrail/server.env` automatically.",
    "2. Run `./agentrail agent create` to choose a runner, choose permissions, and create another local agent.",
    "   AgentRail writes `~/.agentrail/agents/<agentId>.env` for you and can also refresh `~/.agentrail/agent.env` as the default local alias.",
    "   Make sure you are already signed in to the runner you choose on this machine.",
    "3. Run `./agentrail doctor`; setup is only complete when `/tasks/mine?status=in_progress&limit=1` returns assigned work for that agent.",
    "4. Optionally connect GitHub immediately from the init follow-up prompt, or use `./agentrail provider connect github` or `./agentrail provider connect circleci` later.",
    "5. Provider secrets stay out of `config.json` and are written only to `~/.agentrail/provider.env`.",
    `6. For automation or CI, you can still reproduce this setup non-interactively with: \`${renderPortableInitCommand(config)}\`.`,
    "",
  ].join("\n");
}

function renderDefaultRecipe(): string {
  return [
    "# AgentRail Agent Instructions",
    "",
    "This file is passed to local runners created by AgentRail.",
    "Add shared operating guidance for your agents here.",
    "",
  ].join("\n");
}

function toGitHubUrl(slug: string): string {
  return slug ? `https://github.com/${slug}` : "";
}

function renderPortableInitCommand(config: SetupConfig): string {
  const parts = [
    "agentrail init",
    `--mode ${config.mode}`,
    `--base-url ${config.server.baseUrl}`,
    `--port ${config.server.port}`,
    `--persistence ${config.persistence.kind}`,
    '--repo "$PWD"',
    `--repo-allowlist ${config.repos.map((repo) => repo.slug).join(",")}`,
    `--default-branch ${config.repos[0]?.defaultBranch ?? "main"}`,
  ];

  if (config.providers.github.mode !== "real") {
    parts.push(`--provider-mode ${config.providers.github.mode}`);
  }

  if (config.exports.markdown.enabled) {
    parts.push("--markdown-export");
  }

  return parts.join(" ");
}
